### ISSUE TITLE
Problem: custom IMDS client implementation

### ISSUE THREAD

**Issue by tomtau** [crypto-com/tmkms-light#287]
The Nitro helper uses a custom client for obtaining AWS credentials for KMS: https://github.com/crypto-com/tmkms-light/blob/main/providers/nitro/nitro-helper/src/key_utils.rs#L10
The mentioned issue is resolved and IMDS is supported in the official SDK: https://docs.rs/aws-config/0.9.0/aws_config/imds/index.html so it should be possible to use it.

**Comment by allthatjazzleo** [comment]
working on it
