### ISSUE TITLE
Problem: init command doesn't check if vsock-proxy is running

### ISSUE THREAD

**Issue by tomtau** [crypto-com/tmkms-light#307]
`init` needs vsock-proxy, as the enclave contacts AWS KMS. It'd good to run https://github.com/crypto-com/tmkms-light/blob/main/providers/nitro/nitro-helper/src/command.rs#L107 and report an error if it's not running (or attempt to start it like with launch-all: https://github.com/crypto-com/tmkms-light/blob/main/providers/nitro/nitro-helper/src/command/nitro_enclave.rs#L172 ?)

**Comment by allthatjazzleo** [comment]
Before we run `init`, we need both `nitro-cli run-enclave` and `vsock-proxy`. 
We can run both like with launch-all

**Comment by tomtau** [comment]
Yeah, I guess the best will be to check and report an error that will suggest to use `launch-all`
