### ISSUE TITLE
Problem: possible panics in the Nitro log server's tracing layer

### ISSUE THREAD

**Issue by tomtau** [crypto-com/tmkms-light#408]
https://github.com/crypto-com/tmkms-light/blob/main/providers/nitro/nitro-helper/src/tracing_layer.rs#L312 and other places
this may be outside of the bounds: https://github.com/crypto-com/tmkms-light/blob/main/providers/nitro/nitro-helper/src/tracing_layer.rs#L297

**Comment by allthatjazzleo** [comment]
@tomtau 
Outside of the [bounds](https://github.com/crypto-com/tmkms-light/blob/main/providers/nitro/nitro-helper/src/tracing_layer.rs#L297) only occurs when the nitro tmkms run on 32bit system?

**Comment by tomtau** [comment]
@allthatjazzleo those panics could also occur if a different process writes to that vsock port
